### ISSUE TITLE
Preprocessing scripts are missing

### ISSUE THREAD

**Issue by lambdaofgod** [Matyyas/short_text_topic_modeling#2]
You didn't include preprocessing.py, so notebook fails:

> ModuleNotFoundError: No module named 'preprocessing'

**Comment by Toooodd** [comment]
I have the same problem

**Comment by mamrou** [comment]
Hi,

I built those functions inside my company's source code and can't share them publicly. However, you should be able to reproduce by following the preprocessing steps available in the medium [article](https://towardsdatascience.com/short-text-topic-modeling-70e50a57c883).

Let me know 🙂

**Comment by lambdaofgod** [comment]
Proprietary scripts for preprocessing 20 newsgroups? Seriously?

Could you provide a dump of preprocessed csv?
